# an URL we can use to access the service through a web caching proxy
# For example:  /usr/local/sbin/varnishd -a localhost:9000 -f varnish-example.vcl
cache_endpoint = "http://localhost:9000/"

# More specific prefixes must be specified first. Each must end in /.
app_path_prefixes = [
    "/images/v1/",
    "/"
]

cache_control_override = "public, max-age=2592000" # 30d
default_quality = 85
max_pixel_ratio = 2 # provide up to @2x images
origin_request_connect_timeout_seconds = 5.0 # global, not overrideable by tenant, default is 5 seconds
origin_request_timeout_seconds = 5.0 # global, not overrideable by tenant, default is 5 seconds
origin_request_max_keepalive_connections = 10 # global, not overrideable by tenant, default 10, set to 0 for unlimited connections
origin_request_max_connections = 100 # global, not overrideable by tenant, default 100, set to 0 for unlimited connections
origin_request_http2 = false # global, not overrideable by tenant, default false
# origin_request_local_address = "0.0.0.0" # global, not overrideable by tenant, default is unset. Use 0.0.0.0 to force IPv4 requests, :: to force IPv6

# sentry_dsn = "https://…" # enable sentry by configuring a dsn
# sentry_traces_sample_rate = 0.2 # enable tracing by configuring a sample rate

[encryption]
key = "01234567890123456789012345678901" # 32 hex digits (128 bits)
username = "admin" # these credentials are for the endpoint used to encrypt URLs
password = "admin"
url_prefix = "https://images.example.com/images/v1/" # the canonical prefix added to encrypted urls. Must end in /.
# asset_url_prefix = "https://assets.example.com/assets/v1/" # the canonical prefix added to encrypted asset urls. Defaults to url_prefix.

[tenants.cover-images]
origin = "https://storage.example.com/cover-originals/"
default_quality = 90
max_pixel_ratio = 3
# proxy = "http://user:pass@my-proxy.example.com:8888/" # if set, uses an upstream proxy for this tenant
# default_format = "jpeg" # if set, images are converted to this format by default
